blank_issues_enabled: true
contact_links:
  - name: GitHub Discussions
    url: https://github.com/KuchenGamesDE/discussions
    about: Start a discussion
  - name: Discord support server
    url: https://discord.kuchengames.de
    about: The best place to go for help installing or using KuchenGamesDE's softwares.
